package com.example.psktask.mybatis.dao;

import com.example.psktask.entities.Course;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    int deleteById(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    int create(Course course);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    Course findById(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    List<Course> findAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    int save(Course record);
}