package com.example.psktask.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.ID
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.NAME
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.SPECIALTY
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    private String specialty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.YEAR
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    private Long universityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.ID
     *
     * @return the value of PUBLIC.COURSE.ID
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.ID
     *
     * @param id the value for PUBLIC.COURSE.ID
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.NAME
     *
     * @return the value of PUBLIC.COURSE.NAME
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.NAME
     *
     * @param name the value for PUBLIC.COURSE.NAME
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.SPECIALTY
     *
     * @return the value of PUBLIC.COURSE.SPECIALTY
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.SPECIALTY
     *
     * @param specialty the value for PUBLIC.COURSE.SPECIALTY
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.YEAR
     *
     * @return the value of PUBLIC.COURSE.YEAR
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.YEAR
     *
     * @param year the value for PUBLIC.COURSE.YEAR
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @return the value of PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @param universityId the value for PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @mbg.generated Sun Apr 07 17:04:56 EEST 2024
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }
}